INFO	2023-01-10 10:33:11,953	[Server.py:42]	['appium -p 4723  -U 127.0.0.1:21503', 'appium -p 4740  -U 127.0.0.1:21513']
WARNING	2023-01-10 10:33:16,298	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022CCAF26388>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
WARNING	2023-01-10 10:33:18,305	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022CCAF0BAC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
WARNING	2023-01-10 10:33:20,308	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022CCAF3F1C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
INFO	2023-01-10 10:33:24,747	[Server.py:42]	['appium -p 4723  -U 127.0.0.1:21503', 'appium -p 4740  -U 127.0.0.1:21513']
WARNING	2023-01-10 10:59:34,044	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D6E71A5708>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
WARNING	2023-01-10 10:59:36,062	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D6E71C3688>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
WARNING	2023-01-10 10:59:38,065	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D6E71C3D48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
